package io.github.steveplays28.noisium.server.world.chunk.event;

import dev.architectury.event.Event;
import dev.architectury.event.EventFactory;
import net.minecraft.world.chunk.WorldChunk;

public interface NoisiumServerChunkEvent {
	/**
	 * @see WorldChunkGenerated
	 */
	Event<WorldChunkGenerated> WORLD_CHUNK_GENERATED = EventFactory.createLoop();

	@FunctionalInterface
	interface WorldChunkGenerated {
		/**
		 * Invoked after a {@link WorldChunk} has been generated by {@link io.github.steveplays28.noisium.server.world.NoisiumServerWorldChunkManager}.
		 *
		 * @param worldChunk The generated {@link WorldChunk}.
		 */
		void onWorldChunkGenerated(WorldChunk worldChunk);
	}
}
